const QUERY_CONSTANTS = {
  TOXICOLOGY_IND_PROJECT_LIST: 'TOXICOLOGY_IND_PROJECT_LIST',
  TOXICOLOGY_IND_PROJECT_INFO_DETAIL: 'TOXICOLOGY_IND_PROJECT_INFO_DETAIL',
};

export default QUERY_CONSTANTS;
