declare namespace Countries {
  type T =
    /** 特殊 */
    | 'global'
    | 'EU'
    | 'GHTF'
    | 'IMDRF'

    /** 国家 */
    | 'Kazakhstan'
    | 'Keeling Islands'
    | 'Kenya'
    | 'Kiribati'
    | 'Kosovo'
    | 'Kuwait'
    | 'Kyrgyzstan'
    | 'Laos'
    | 'Latvia'
    | 'Lebanon'
    | 'Lesotho'
    | 'Liberia'
    | 'Libya'
    | 'Liechtenstein'
    | 'Lithuania'
    | 'Luxembourg'
    | 'Macao'
    | 'Macedonia'
    | 'Madagascar'
    | 'Malawi'
    | 'Malaysia'
    | 'Maldives'
    | 'Mali'
    | 'Malta'
    | 'Marshall Islands'
    | 'Martinique'
    | 'Mauritania'
    | 'Mauritius'
    | 'Mayotte'
    | 'Mexico'
    | 'Micronesia'
    | 'Moldova'
    | 'Monaco'
    | 'Mongolia'
    | 'Montenegro'
    | 'Montserrat'
    | 'Morocco'
    | 'Mozambique'
    | 'Myanmar'
    | 'Namibia'
    | 'Nauru'
    | 'Nepal'
    | 'Netherlands'
    | 'New Caledonia'
    | 'New Zealand'
    | 'Nicaragua'
    | 'Niger'
    | 'Nigeria'
    | 'Niue'
    | 'Norfolk Island'
    | 'North Korea'
    | 'Northern Cyprus'
    | 'Northern Mariana Islands'
    | 'Norway'
    | 'Oman'
    | 'Pakistan'
    | 'Palau'
    | 'PanAfrica'
    | 'Panama'
    | 'Papua New Guinea'
    | 'Paraguay'
    | 'Peru'
    | 'Philippines'
    | 'Pitcairn'
    | 'Poland'
    | 'Portugal'
    | 'Puerto Rico'
    | 'Qatar'
    | 'Republic of Serbia'
    | 'Republic of the Congo'
    | 'Reunion'
    | 'Réunion'
    | 'Romania'
    | 'Russia'
    | 'Rwanda'
    | 'Saint Barthelemy'
    | 'Saint Barthélemy'
    | 'Saint Helena'
    | 'Saint Kitts and Nevis'
    | 'Saint Lucia'
    | 'Saint Martin'
    | 'Saint Pierre and Miquelon'
    | 'Saint Vincent and the Grenadines'
    | 'Samoa'
    | 'San Marino'
    | 'Sao Tome and Principe'
    | 'Saudi Arabia'
    | 'Senegal'
    | 'Seychelles'
    | 'Sierra Leone'
    | 'Singapore'
    | 'Sint Maarten'
    | 'Slovakia'
    | 'Slovenia'
    | 'Solomon Islands'
    | 'Somalia'
    | 'Somaliland'
    | 'South Africa'
    | 'South Georgia and the South Sandwich Islands'
    | 'South Korea'
    | 'South Sudan'
    | 'Spain'
    | 'Sri Lanka'
    | 'Sudan'
    | 'Suriname'
    | 'Svalbard and Jan Mayen'
    | 'Swaziland'
    | 'Sweden'
    | 'Switzerland'
    | 'Syria'
    | 'Taiwan'
    | 'Tajikistan'
    | 'Thailand'
    | 'The Bahamas'
    | 'Togo'
    | 'Tokelau'
    | 'Tonga'
    | 'Trinidad and Tobago'
    | 'Tristan da Cunha'
    | 'Tunisia'
    | 'Turkey'
    | 'Turkmenistan'
    | 'Turks and Caicos Islands'
    | 'Tuvalu'
    | 'Uganda'
    | 'Ukraine'
    | 'United Arab Emirates'
    | 'United Kingdom'
    | 'United Republic of Tanzania'
    | 'United States Minor Outlying Islands'
    | 'United States of America'
    | 'United States Virgin Islands'
    | 'Uruguay'
    | 'Uzbekistan'
    | 'Vanuatu'
    | 'Venezuela'
    | 'Vietnam'
    | 'Virgin Islands British'
    | 'Wallis and Futuna'
    | 'West Bank'
    | 'Western Sahara'
    | 'Yemen'
    | 'Zambia'
    | 'Zimbabwe'
    | 'Afghanistan'
    | 'Africa'
    | 'Aland Islands'
    | 'Åland Islands'
    | 'Albania'
    | 'Algeria'
    | 'American Samoa'
    | 'Andorra'
    | 'Angola'
    | 'Anguilla'
    | 'Antigua and Barbuda'
    | 'Argentina'
    | 'Armenia'
    | 'Aruba'
    | 'Ascension'
    | 'Australia'
    | 'Austria'
    | 'Azerbaijan'
    | 'Bahrain'
    | 'Bangladesh'
    | 'Barbados'
    | 'Belarus'
    | 'Belgium'
    | 'Belize'
    | 'Benin'
    | 'Bermuda'
    | 'Bhutan'
    | 'Bolivia'
    | 'Bonaire Sint Eustatius and Saba'
    | 'Bosnia and Herzegovina'
    | 'Botswana'
    | 'Bouvet Island'
    | 'Brazil'
    | 'British Indian Ocean Territory'
    | 'Brunei'
    | 'Bulgaria'
    | 'Burkina Faso'
    | 'Burundi'
    | 'Cabo Verde'
    | 'Cambodia'
    | 'Cameroon'
    | 'Canada'
    | 'Cayman Islands'
    | 'Central African Republic'
    | 'Chad'
    | 'Chile'
    | 'China'
    | 'Christmas Island'
    | 'Cocos Islands'
    | 'Colombia'
    | 'Comoros'
    | 'Cook Islands'
    | 'Costa Rica'
    | 'Croatia'
    | 'Cuba'
    | 'Curacao'
    | 'Curaçao'
    | 'Cyprus'
    | 'Czech Republic'
    | 'Democratic Republic of the Congo'
    | 'Denmark'
    | 'Djibouti'
    | 'Dominica'
    | 'Dominican Republic'
    | 'East Timor'
    | 'Ecuador'
    | 'Egypt'
    | 'El Salvador'
    | 'Equatorial Guinea'
    | 'Eritrea'
    | 'Estonia'
    | 'Ethiopia'
    | 'Falkland Islands'
    | 'Faroe Islands'
    | 'Fiji'
    | 'Finland'
    | 'France'
    | 'French Guiana'
    | 'French Polynesia'
    | 'French Southern and Antarctic Lands'
    | 'Gabon'
    | 'Gambia'
    | 'Georgia'
    | 'Germany'
    | 'Ghana'
    | 'Gibraltar'
    | 'Greece'
    | 'Greenland'
    | 'Grenada'
    | 'Guadeloupe'
    | 'Guam'
    | 'Guatemala'
    | 'Guernsey'
    | 'Guinea'
    | 'Guinea Bissau'
    | 'Guyana'
    | 'Haiti'
    | 'Heard Island and McDonald Islands'
    | 'Holy see'
    | 'Honduras'
    | 'HongKong'
    | 'Hungary'
    | 'Iceland'
    | 'India'
    | 'Indonesia'
    | 'Iran'
    | 'Iraq'
    | 'Ireland'
    | 'Isle of Man'
    | 'Israel'
    | 'Italy'
    | 'Ivory Coast'
    | 'Jamaica'
    | 'Japan'
    | 'Jersey'
    | 'Jordan';
}
